<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Agent Transactions Report</title>
    <link rel="stylesheet" href="{{ public_path('css/agent_transactions_pdf.css') }}">
</head>

<body>
    <div class="header">
        <h1>Agent Transactions Report</h1>
    </div>

    <div class="agent-info">
        <table>
            <tr>
                <td class="label">Agent:</td>
                <td>{{ $agentName }}</td>
                <td class="label">Date Range:</td>
                <td>{{ $dateRange }}</td>
            </tr>
        </table>
    </div>

    @if ($transactions->count() > 0)
        <table class="report-table">
            <thead>
                <tr>
                    <th style="width: 10px;">No</th>
                    <th style="width: 80px;">Date</th>
                    <th style="width: 100px;">Type</th>
                    <th style="width: 120px;">Reference</th>
                    <th style="width: 100px;">Payment Mode</th>
                    <th style="width: 100px;" class="text-right">Amount (₹)</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($transactions as $key => $transaction)
                    @php
                        $formattedDate = \Carbon\Carbon::parse($transaction->date)->format('d-m-Y');
                        $formattedAmount = '₹' . number_format($transaction->amount, 2);
                    @endphp
                    <tr>
                        <td>{{ $key + 1 }}</td>
                        <td>{{ $formattedDate }}</td>
                        <td>
                            @if ($transaction->type == 'Estimate')
                                <span class="badge badge-estimate">Estimate</span>
                            @else
                                <span class="badge badge-collection">Collection</span>
                            @endif
                        </td>
                        <td>
                            {{ $transaction->reference }}
                            <br>
                        </td>
                        <td>
                            @if ($transaction->type == 'Collection' && $transaction->payment_mode)
                                <span class="payment-mode">{{ $transaction->payment_mode }}</span>
                            @else
                                <span>-</span>
                            @endif
                        </td>
                        <td class="text-right">
                            <strong
                                class="{{ $transaction->type == 'Collection' ? 'type-collection' : 'type-estimate' }}">
                                {{ $formattedAmount }}
                            </strong>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="stats">
            <table>
                <tr>
                    <td class="label">Total Estimates</td>
                    <td class="label">Total Collections</td>
                    <td class="label">Net Balance</td>
                    <td class="label">Total Records</td>
                </tr>
                <tr>
                    <td class="value positive">₹{{ number_format($totalEstimates, 2) }}</td>
                    <td class="value positive">₹{{ number_format($totalCollections, 2) }}</td>
                    <td class="value {{ $netBalance >= 0 ? 'positive' : 'negative' }}">
                        ₹{{ number_format(abs($netBalance), 2) }}
                        @if ($netBalance < 0)
                            <br><small>(Due)</small>
                        @endif
                    </td>
                    <td class="value">{{ $transactions->count() }}</td>
                </tr>
            </table>
        </div>
    @else
        <div style="text-align: center; padding: 40px; background-color: #f8f9fa; border: 1px solid #dee2e6;">
            <h3>No transactions found</h3>
            <p>No records match the selected criteria.</p>
        </div>
    @endif

    <div class="footer">
        Page 1 of 1 • Generated by Mohidh Crackers System • {{ date('Y') }}
    </div>
</body>

</html>
